version: '4'

services:
  app:
    build: .
    ports:
      - '3080:3080'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
