version: '3'

services:
  app:
    build: .
    ports:
      - '3080:3080'
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
